package com.mqa.android.kade.model

data class DetailEvent(val strHomeTeam: String,
                       val strAwayTeam: String,
                       val intHomeScore: String,
                       val intAwayScore: String,
                       val dateEvent: String,
                       val strHomeGoalDetails: String,
                       val intHomeShots: String,
                       val strHomeLineupGoalkeeper: String,
                       val strHomeLineupDefense: String,
                       val strHomeLineupMidfiel: String,
                       val strHomeLineupForward: String,
                       val strHomeLineupSubstitutes: String,
                       val strAwayGoalDetails: String,
                       val intAwayShots: String,
                       val strAwayLineupGoalkeeper: String,
                       val strAwayLineupDefense: String,
                       val strAwayLineupMidfiel: String,
                       val strAwayLineupForward: String,
                       val strAwayLineupSubstitutes: String,
                       val idHomeTeam: String,
                       val idAwayTeam: String,
                       val idEvent: String)